main:
    steps:
        - init:
              assign:
                  - cloud_run_base_url: ${sys.get_env("CLOUD_RUN_BASE_URL")}
                  - bq_project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
                  - bq_dataset_id: ${sys.get_env("BQ_DATASET")}
                  - bq_ar_table_id: ${sys.get_env("BQ_AR_TABLE_NAME")}
                  - table_ar: '${bq_project_id + "." + bq_dataset_id + "." + bq_ar_table_id}'
                  - bq_us_table_id: ${sys.get_env("BQ_US_TABLE_NAME")}

        - us_market_branch:
              steps:
                    - get_symbols:
                        call: query_database
                        args:
                            full_table_name: '${bq_project_id + "." + bq_dataset_id + "." + bq_us_table_id}'
                            bq_project_id: ${bq_project_id}
                        result: us_symbols

                    - get_new_values:
                        switch:
                            - condition: ${len(us_symbols) > 0}
                              steps:
                                    - init_us_market:
                                            assign:
                                                - us_market_values: []
                                    - iterate_symbols:
                                        for:
                                            value: row
                                            in: ${us_symbols}
                                            steps:
                                                - init_iterate_symbols:
                                                    assign:
                                                        - symbol: ${row.f[0].v}
                                                - call_function:
                                                    call: av_api_call
                                                    args:
                                                        symbol: ${symbol}
                                                        cloud_run_base_url: ${cloud_run_base_url}
                                                    result: av_response
                                                - prepare_next:
                                                      assign:
                                                          - new_value: ['${av_response.ticker}', '${av_response.price}', 'US', '${av_response.date}']
                                                          - us_market_values: ${list.concat(us_market_values, new_value)}
                                    

                            - condition: ${true}
                              steps:
                                    - log_no_av_symbols:
                                        call: sys.log
                                        args:
                                            text: "No symbols found in BigQuery to process for Alpha Vantage."
                    - write_new_values:
                        call: http.post
                        args:
                            url: ${cloud_run_base_url + "/bq-batch-load"}
                            auth:
                                type: OIDC
                            timeout: 1800
                            body:
                                symbols:  ${us_market_values}
                            headers: 
                                Content-Type: application/json

                        result: av_response
                    

query_database:
    params: [full_table_name, bq_project_id]
    steps:
        - init:
            assign:
                - url: '${"https://bigquery.googleapis.com/bigquery/v2/projects/" + bq_project_id + "/queries"}'
        - runQuery:
            call: http.post
            args:
                url: ${url}
                auth:
                    type: OAuth2
                    scopes: https://www.googleapis.com/auth/drive.readonly,https://www.googleapis.com/auth/bigquery
                body:
                    useLegacySql: false
                    query: '${"SELECT symbol FROM `"+full_table_name+"`"}'
            result: queryResult
        - done:
              return: ${queryResult.body.rows}

av_api_call:
    params: [symbol, cloud_run_base_url]
    steps:
        - call_api:
            try:
                call: http.get
                args:
                    url: ${cloud_run_base_url + "/alpha-vantage" + "?symbol=" + symbol}
                    auth:
                        type: OIDC
                    timeout: 1800
                result: av_response
            except:
                as: e
                steps:
                    - log_av_cr_call_error:
                        call: sys.log
                        args:
                            text: '${"Error calling Alpha Vantage Cloud Run endpoint with symbol list: " + e.message + "; Response: " + json.encode_to_string(e)}'
                    - known_errors:
                        switch:
                            - condition: ${not("HttpError" in e.tags)}
                              next: connection_problem
                            - condition: ${e.code == 404}
                              next: url_not_found
                            - condition: ${e.code == 403}
                              next: auth_problem
                    - unhandled_exception:
                        raise: ${e}

        - log_api_calls_response:
            call: sys.log
            args:
                  text: '${"AV Response: " + json.encode_to_string(av_response)}'
        - done:
              return: ${av_response.body}
        - connection_problem:
            return: "Connection problem; check URL"
        - url_not_found:
            return: "Sorry, URL wasn't found"
        - auth_problem:
            return: "Authentication error"