[project]
name = "financemonitor-helpers"
version = "0.1.0"
description = "Shared libraries to be included in the code."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "requests-mock>=1.12.1",
]
[tool.uv]
package = true
[tool.pytest.ini_options]
pythonpath = ["src"]
