[project]
name = "alphavantage"
version = "0.1.0"
description = "Alpha Vantage API client library"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.31.0",
    "requests-mock>=1.12.1",
    "pandas>=2.3.3",
]
